name: sea_cinema_frontend
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  carousel_slider: ^4.1.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  flutter_svg: ^0.23.0+1
  get: 4.6.5
  get_storage: 2.0.3
  google_fonts: ^2.2.0
  http: ^0.13.6
  http_parser: ^4.0.2
  image_picker: ^0.8.4+4
  intl: ^0.18.1
  selectable_box: ^1.0.0
  shared_preferences: ^2.1.2
  supercharged: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
